name: 构建与发布

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: 使用 Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: 安装依赖
      run: npm ci
      
    - name: 代码检查
      run: |
        npm i @typescript-eslint/eslint-plugin @typescript-eslint/parser -D
        npm run lint
      
    - name: 构建
      run: npm run build
    
    - name: 检查版本变更
      id: check-version
      run: |
        # 获取最近的提交信息
        COMMIT_MSG=$(git log -1 --pretty=%B)
        echo "提交信息: $COMMIT_MSG"
        
        # 使用正则表达式检查提交信息是否包含版本更新的标记
        if [[ $COMMIT_MSG =~ chore\(release\):\ 升级版本至\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
          VERSION="${BASH_REMATCH[1]}"
          echo "检测到版本更新: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "updated=true" >> $GITHUB_OUTPUT
        else
          echo "未检测到版本更新提交"
          echo "updated=false" >> $GITHUB_OUTPUT
        fi
    
    - name: 创建 GitHub Release
      id: create_release
      if: steps.check-version.outputs.updated == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.check-version.outputs.version }}
        release_name: 版本 v${{ steps.check-version.outputs.version }}
        body: |
          版本 v${{ steps.check-version.outputs.version }} 发布
        draft: false
        prerelease: false

    - name: 发布 NPM 包
      if: steps.check-version.outputs.updated == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}